name: Java CI with Gradle

on:
  push:
    branches: [ "1.21.1" ]
  pull_request:
    branches: [ "1.21.1" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Stop any existing Gradle daemons
        run: gradle --stop

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle 8.5
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.5'

      - name: Set Gradle user home inside workspace
        run: echo "ORG_GRADLE_PROJECT_gradle_user_home=${{ github.workspace }}/.gradle" >> $GITHUB_ENV

      - name: Build with Gradle
        run: gradle build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build   # run after build to avoid cache locks

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle 8.5
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.5'

      - name: Set Gradle user home inside workspace
        run: echo "ORG_GRADLE_PROJECT_gradle_user_home=${{ github.workspace }}/.gradle" >> $GITHUB_ENV

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          gradle-version: '8.5'
          build-root-directory: .